runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: blog.app

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
